/**
 * Curated list of the most popular Google Fonts (300+).
 * Used for autocomplete in the Brand Design font picker.
 * Source: Google Fonts top fonts by popularity.
 */
export const GOOGLE_FONTS: string[] = [
  // Sans-serif
  "Roboto",
  "Open Sans",
  "Noto Sans",
  "Montserrat",
  "Lato",
  "Poppins",
  "Inter",
  "Raleway",
  "Nunito",
  "Ubuntu",
  "Rubik",
  "Source Sans 3",
  "Mulish",
  "Quicksand",
  "Jost",
  "DM Sans",
  "Manrope",
  "Outfit",
  "Plus Jakarta Sans",
  "Figtree",
  "Barlow",
  "Exo 2",
  "Josefin Sans",
  "Nunito Sans",
  "Work Sans",
  "Karla",
  "Cabin",
  "Oxygen",
  "Hind",
  "Fira Sans",
  "Nanum Gothic",
  "Titillium Web",
  "Muli",
  "Varela Round",
  "Arimo",
  "Questrial",
  "Scada",
  "Asap",
  "Asap Condensed",
  "Be Vietnam Pro",
  "Faustina",
  "Heebo",
  "IBM Plex Sans",
  "Kanit",
  "Kumbh Sans",
  "Lexend",
  "Libre Franklin",
  "Mada",
  "Maven Pro",
  "Mukta",
  "Noto Sans JP",
  "Noto Sans KR",
  "Noto Sans TC",
  "Overpass",
  "Public Sans",
  "Red Hat Display",
  "Sora",
  "Space Grotesk",
  "Spline Sans",
  "Tajawal",
  "Yanone Kaffeesatz",
  "Zilla Slab",
  "Libre Baskerville",
  "Prompt",
  "Signika",
  "Teko",
  "Urbanist",
  "Ysabeau",
  "Ysabeau Office",
  "Albert Sans",
  "Alexandria",
  "Bricolage Grotesque",
  "Chivo",
  "Climate Crisis",
  "Geologica",
  "Geist",
  // Serif
  "Merriweather",
  "Playfair Display",
  "Lora",
  "PT Serif",
  "Roboto Slab",
  "Source Serif 4",
  "Bitter",
  "Arvo",
  "Crimson Text",
  "Vollkorn",
  "Cardo",
  "Cormorant",
  "Cormorant Garamond",
  "Domine",
  "EB Garamond",
  "GFS Didot",
  "Gentium Book Plus",
  "Gilda Display",
  "IBM Plex Serif",
  "Libre Baskerville",
  "Lustria",
  "Neuton",
  "Noto Serif",
  "Old Standard TT",
  "Palatino Linotype",
  "Petrona",
  "Spectral",
  "Unna",
  "Yeseva One",
  "Zilla Slab Highlight",
  "Martel",
  "Podkova",
  "Sorts Mill Goudy",
  "Tinos",
  "Vidaloka",
  // Display / Decorative
  "Bebas Neue",
  "Anton",
  "Abril Fatface",
  "Alfa Slab One",
  "Baloo 2",
  "Bangers",
  "Boogaloo",
  "Chakra Petch",
  "Cinzel",
  "Comfortaa",
  "Concert One",
  "Edu NSW ACT Foundation",
  "Encode Sans",
  "Fredoka",
  "Gochi Hand",
  "Graduate",
  "Hanken Grotesk",
  "Ibarra Real Nova",
  "Italiana",
  "Kaushan Script",
  "League Spartan",
  "Lilita One",
  "Lobster",
  "Lobster Two",
  "Mochiy Pop One",
  "Oleo Script",
  "Orbitron",
  "Oswald",
  "Pacifico",
  "Patrick Hand",
  "Permanent Marker",
  "Piazzolla",
  "Righteous",
  "Rowdies",
  "Russo One",
  "Saira",
  "Saira Condensed",
  "Shadows Into Light",
  "Sigmar",
  "Syne",
  "Titan One",
  "Ultra",
  "Viga",
  "Yrsa",
  "Zeyada",
  // Monospace
  "Roboto Mono",
  "Source Code Pro",
  "Fira Code",
  "IBM Plex Mono",
  "Space Mono",
  "JetBrains Mono",
  "Courier Prime",
  "DM Mono",
  "Inconsolata",
  "PT Mono",
  "Red Hat Mono",
  "Share Tech Mono",
  "Ubuntu Mono",
  // Handwriting / Script
  "Dancing Script",
  "Pacifico",
  "Great Vibes",
  "Caveat",
  "Sacramento",
  "Allura",
  "Courgette",
  "Handlee",
  "Marck Script",
  "Merienda",
  "Niconne",
  "Pinyon Script",
  "Satisfy",
  "Tangerine",
  "Yellowtail",
  "Cookie",
  "Devonshire",
  "Euphoria Script",
  "Inspiration",
  "La Belle Aurore",
  "League Script",
  "Lovers Quarrel",
  "Ms Madi",
  "Norican",
  "Over the Rainbow",
  "Princess Sofia",
  "Questrial",
  "Rouge Script",
  "Seaweed Script",
  "Stalemate",
  "Waiting for the Sunrise",
  "WindSong",
  "Ysabeau Infant",
  // Condensed / Narrow
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Exo",
  "Fjalla One",
  "News Cycle",
  "Pathway Gothic One",
  "Saira Extra Condensed",
  "Squada One",
  // Extended / Wide
  "Jura",
  "Readex Pro",
  "Schibsted Grotesk",
  "Sen",
  "Wix Madefor Display",
  "Wix Madefor Text",
].sort((a, b) => a.localeCompare(b));

/** Build a Google Fonts embed URL for one or more font families */
export function buildGoogleFontsUrl(families: string[]): string {
  const unique = [...new Set(families.filter(Boolean))];
  if (!unique.length) return "";
  const params = unique
    .map((f) => `family=${encodeURIComponent(f)}:wght@300;400;500;600;700`)
    .join("&");
  return `https://fonts.googleapis.com/css2?${params}&display=swap`;
}

/** Inject a Google Fonts stylesheet link into <head> (idempotent by href) */
export function injectGoogleFont(family: string): void {
  if (!family) return;
  const url = buildGoogleFontsUrl([family]);
  const existing = document.querySelector(`link[href="${url}"]`);
  if (existing) return;
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = url;
  document.head.appendChild(link);
}
